### ISSUE TITLE
/imgs has no meta file

### ISSUE THREAD

**Issue by ztffn** [shinn716/CustomTimelineTools#1]
"Asset Packages/com.shinn.timeline/imgs has no meta file, but it's in an immutable folder. The asset will be ignored."

All .png's in the folder produces the same error, resulting in ≈40 errors

**Comment by shinn716** [comment]
Hello ZTIF, 
I have created a new branch for package only. This branch will ignore images folder and unused files.
You can reimport new version from  
https://github.com/shinn716/CustomTimelineTools.git#package

![Snipaste_2022-03-15_08-58-31](https://user-images.githubusercontent.com/3417707/158285319-c86d5c8f-8692-46bb-a76c-9d4f9c4fddf7.png)
Thanks.
